### ISSUE TITLE
There are some broken image links

### ISSUE THREAD

**Issue by dwangywu** [UCSBCarpentry/2019-04-11-UCSB-SW-Workshop#1]
Please delete the text below before submitting your contribution. 

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

If this issue is about a specific episode within a lesson, please provide its link or filename.

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  

---

**Comment by ilessing** [comment]
At what URLs are you seeing broken images?

**Comment by dwangywu** [comment]
https://ucsbcarpentry.github.io/2019-04-11-UCSB-SW-Workshop/shell-novice/02-filedir/

**Comment by ilessing** [comment]
I did a right-click on one of the broken images and selected   _copy image address_
which gave me:  `https://ucsbcarpentry.github.io/2019-04-11-UCSB-SW-Workshop/shell-novice/fig/home-directories.svg`
The file doesn't exist in `/shell-novice/fig/`.
I can see that file (`home-directories.svg`) exists already in `2019-04-11-UCSB-SW-Workshop/fig/` so we just need to correct the reference to _go up 1 directory_

The file reference is in `_episodes/shell-novice/02-filedir.md` at line number 110

change:
```
![Home Directories](../fig/home-directories.svg)
```

to:

```
![Home Directories](../../fig/home-directories.svg)
````

and now the  home-directories.svg image does show up.  (see screenshot)
Now there are a bunch of other image references to fix.  :-P

<img width="1119" alt="Screen-Shot-2019-03-27-at-12 01 26-PM" src="https://user-images.githubusercontent.com/275899/55104992-b42af800-5088-11e9-85f0-344d9beb791c.png">

**Comment by dwangywu** [comment]
Many thanks!

Ian Lessing <notifications@github.com> 于 2019年3月27日 周三 12:06写道：

**Comment by ilessing** [comment]
I've corrected some more image references with e80765da34936.  Are there any more broken images?

**Comment by dwangywu** [comment]
I will check it, if I found more, I will let you know.

Thanks!

Yuan

**Comment by jonjab** [comment]
Closing at our final prep meeting.
