### ISSUE TITLE
There is no ether pad link

### ISSUE THREAD

**Issue by dwangywu** [UCSBCarpentry/2019-04-11-UCSB-SW-Workshop#2]
Please delete the text below before submitting your contribution. 

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

If this issue is about a specific episode within a lesson, please provide its link or filename.

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  

---

**Comment by ilessing** [comment]
The etherpad link should be specified in `index.md` file in the `collaborative_notes` field.

see [Sharon's commit from last week](https://github.com/UCSBCarpentry/2019-03-21-UCSBLibrary/commit/cd52683703af6b5bd86fc4925bf9b31b5aab1f9f) as an example.

**Comment by dwangywu** [comment]
I put the the link, but somehow it didn't work.

**Comment by ilessing** [comment]
fixing issue #3 also fixed this issue.
