### ISSUE TITLE
Dead links throughout the site

### ISSUE THREAD

**Issue by noah-de** [UCSBCarpentry/2019-04-11-UCSB-SW-Workshop#5]
Checked the website for broken links and found 24.

Checked: https://ucsbcarpentry.github.io/2019-04-11-UCSB-SW-Workshop/

https://www.deadlinkchecker.com/website-dead-link-checker.asp

**Comment by noah-de** [comment]
![dead links](https://user-images.githubusercontent.com/2643768/55904487-cf1b6300-5b84-11e9-8305-07d2df8db3de.png)

**Comment by jonjab** [comment]
Most of these are the 'improve this page' links on the top menu from the R lesson.  It's possibly because those episodes are a level down in the hierarchy?

**Comment by noah-de** [comment]
Good enough.
The class went well
